## Análise com Random Forests no banco de dados de Methylation

In [1]:
#Importando as bibliotecas
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_predict
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn import tree

In [2]:
data = pd.read_csv('methylation-cancer.csv')
data

cd_pessoas  idade  cd_cpg  ilha_cpg     valor  cd_status_mutacao
0                 1     59       1         1  0.835311                  2
1                 1     59       2         1  0.874393                  2
2                 1     59       3         1  0.067613                  2
3                 1     59       4         0  0.162683                  2
4                 1     59       5         1  0.075853                  2
5                 1     59       6         1  0.037293                  2
6                 1     59       7         1  0.964013                  2
7                 1     59       8         1  0.023429                  2
8                 1     59       9         1  0.018629                  2
9                 1     59      10         0  0.671006                  2
10                1     59      11         0  0.878674                  2
11                1     59      12         1  0.022775                  2
12                1     59      13         1  0.017832                  2
13                1     59      14         1  0.020349                  2
14                1     59      15         0  0.858171                  2
15                1     59      16         1  0.023286                  2
16                1     59      17         0  0.838488                  2
17                1     59      18         1  0.127851                  2
18                1     59      19         0  0.862066                  2
19                1     59      20         0  0.165090                  2
20                1     59      21         0  0.892657                  2
21                1     59      22         1  0.026840                  2
22                1     59      23         1  0.024712                  2
23                1     59      24         1  0.499923                  2
24                1     59      25         1  0.038054                  2
25                1     59      26         1  0.044671                  2
26                1     59      27         1  0.031396                  2
27                1     59      28         1  0.360854                  2
28                1     59      29         1  0.058721                  2
29                1     59      30         1  0.117498                  2
...             ...    ...     ...       ...       ...                ...
2122706          84     29   27549         1  0.105686                  0
2122707          84     29   27550         0  0.291930                  0
2122708          84     29   27551         0  0.108988                  0
2122709          84     29   27552         1  0.100107                  0
2122710          84     29   27553         0  0.852534                  0
2122711          84     29   27554         1  0.020359                  0
2122712          84     29   27555         1  0.034191                  0
2122713          84     29   27556         1  0.012621                  0
2122714          84     29   27557         1  0.019313                  0
2122715          84     29   27558         1  0.054471                  0
2122716          84     29   27559         0  0.628964                  0
2122717          84     29   27560         0  0.852660                  0
2122718          84     29   27561         1  0.478049                  0
2122719          84     29   27562         1  0.055539                  0
2122720          84     29   27563         1  0.314078                  0
2122721          84     29   27564         1  0.028800                  0
2122722          84     29   27565         1  0.015117                  0
2122723          84     29   27566         1  0.062860                  0
2122724          84     29   27567         1  0.965189                  0
2122725          84     29   27568         1  0.062152                  0
2122726          84     29   27569         0  0.775138                  0
2122727          84     29   27570         1  0.065570                  0
2122728      

In [3]:
len(data)

2122736

In [12]:
#Separando preditores e a classe
X = data.values[:, 0:4]
Y = data.values[:,5]

In [13]:
X

array([[1.0000e+00, 5.9000e+01, 1.0000e+00, 1.0000e+00],
       [1.0000e+00, 5.9000e+01, 2.0000e+00, 1.0000e+00],
       [1.0000e+00, 5.9000e+01, 3.0000e+00, 1.0000e+00],
       ...,
       [8.4000e+01, 2.9000e+01, 2.7576e+04, 1.0000e+00],
       [8.4000e+01, 2.9000e+01, 2.7577e+04, 1.0000e+00],
       [8.4000e+01, 2.9000e+01, 2.7578e+04, 1.0000e+00]])

In [14]:
Y

array([2., 2., 2., ..., 0., 0., 0.])

In [15]:
X_train, X_test, y_train, y_test = train_test_split( X, Y, test_size = 0.3)

In [16]:
#Aplicando o algoritmo com critério gini
clf_gini = RandomForestClassifier(n_estimators=100, random_state=0, criterion = "gini", max_depth=5)
clf_gini.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=5, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [17]:
#Aplicando o algoritmo com critério entropia
clf_entropia = RandomForestClassifier(n_estimators=100, random_state=0, criterion = "entropy", max_depth=5)
clf_entropia.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=5, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [18]:
#Predição com critério gini_index
y_pred = clf_gini.predict(X_test)
y_pred

array([0., 0., 2., ..., 0., 0., 0.])

In [19]:
#Predição com critério ganho de informação
y_pred_en = clf_entropia.predict(X_test)
y_pred_en

array([0., 0., 2., ..., 0., 0., 0.])

In [22]:
#Acurácia com o critério gini_index
print ("Acurácia foi ", accuracy_score(y_test,y_pred)*100)

Acurácia foi  75.66223475670557


In [23]:
print ("Acurácia foi ", accuracy_score(y_test,y_pred_en)*100)

Acurácia foi  73.5884966105075
